# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Vivere di rendita
email: info@viveredirendita.net
description: > # this means to ignore newlines until "baseurl:"
  Scopri strategie, consigli e strumenti pratici per raggiungere 
  l'indipendenza finanziaria e vivere di rendita. 
  Approfondimenti su investimenti, gestione delle finanze personali 
  e stili di vita sostenibili per realizzare i tuoi obiettivi.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://viveredirendita.net" # the base hostname & protocol for your site

domain: candoni.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://candoni.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /viveredirendita-site/ # place folder name if the site is served in a subfolder

#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
#remote_theme: pages-themes/minimal@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
#google_analytics: [Your Google Analytics tracking ID]